### ISSUE TITLE
Hi,How is the project going on?

### ISSUE THREAD

**Issue by andersling** [jeremydumais/airodb#1]
Do  you have a plan when the first version will be released? Thanks a lot!
  
Looking forward to your great job!

**Comment by jeremydumais** [comment]
Hi @andersling,

I'm looking to release the first version around January 15th.
Thanks for the follow!

Jed

**Comment by andersling** [comment]
Big Thanks to jeremydumais @jeremydumais  !Looking forward for it!

**Comment by jeremydumais** [comment]
Hi @andersling,

The first release of airodb is now available. :)
Do not hesitate to report issues if you find some. 

Regards,
Jed

**Comment by andersling** [comment]
Thank you very much! That is great! a big thanks!

**Comment by andersling** [comment]
it's really useful for me ,thanks!sir

**Comment by jeremydumais** [comment]
Cool! :) Let me know if you think of some ideas to improve the application!
